### ISSUE TITLE
Any idea about the relations between items ?

### ISSUE THREAD

**Issue by fanyike** [cnclabs/ICE#2]
In this paper, the author assume that there exit relations between words ,however , there are relations between items, which is not considered. Can you expand this program to this kind of problem?

**Comment by chihming** [comment]
Actually it is possible. The original paper doesn't consider the item-item connections, but we can write a program (or extend the current program) to construct the graph with item-item connections, and then to feed the graph to ICE execution program. Contribution is also welcome.

In addition, could you provide us what dataset you are considering to apply to? or what dataset consisting of explicit item-item connections?

**Comment by fanyike** [comment]
There are plenty of hetergeneous networks, such as drug and cell line simility network. I think add the connections between items could improve the performance. Really hope 
your program could do that. 



fanyikecsu@gmail.com
 
From: Chih-Ming Chen
Date: 2017-08-28 14:02
To: cnclabs/ICE
CC: yaco; Author
Subject: Re: [cnclabs/ICE] Any idea about the relations between items ? (#2)
Actually it is possible. The original paper doesn't consider the item-item connections, but we can write a program (or extend the current program) to construct the graph with item-item connections, and then to feed the graph to ICE execution program. Contribution is also welcome.
In addition, could you provide us what dataset you are considering to apply to? or what dataset consisting of explicit item-item connections?

**Comment by chihming** [comment]
Hi! We have another project that is able to handle different networks. Please refer to [proNet-core](https://github.com/chihming/proNet-core).
